name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sberczi/calibre2web:$(date "+%y%m%d_%H%M%S") --tag sberczi/calibre2web:latest
    - name: Publish the Docker image
      run: docker push sberczi/calibre2web:latest
